# Google has implemented the open id standardization for its Oauth prototol
# API endpoints have to be updated based on this Discovery Document
# https://accounts.google.com/.well-known/openid-configuration
google:
    auth:
        auth_url:           https://accounts.google.com/o/oauth2/v2/auth
        scope_separator:    " "
        query_params:
            redirect_uri:   /xxxxxxxx
            response_type:  code
            client_id:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            scope:
                -           "openid"
                -           "email"
                -           "profile"
            access_type:    online
    token:
        token_url:          https://www.googleapis.com/oauth2/v4/token
        client_secret:      xxxxxxxxxxxxxxxxxxxxxxx
    api:
        user_info_url:      https://www.googleapis.com/oauth2/v3/userinfo
        geocoding:          https://maps.googleapis.com/maps/api/geocode/json
        timezone:           https://maps.googleapis.com/maps/api/timezone/json
        key:                xxxxxxxxxxxxxxxxxxxxxxxxxxx             # for timezone api & geocoding api
        reCAPTCHA:
            verify_url:     https://www.google.com/recaptcha/api/siteverify
            site_key:       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            secret_key:     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

facebook:
    auth:
        auth_url:           https://www.facebook.com/v3.0/dialog/oauth
        scope_separator:    ","
        query_params:
            redirect_uri:   /xxxxxxxx
            client_id:      !!str 00000000000000
            scope:
                -           email
                -           public_profile
            auth_type:      rerequest
    token:
        token_url:          https://graph.facebook.com/v3.0/oauth/access_token
        client_secret:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api:
        permission:
            url:            https://graph.facebook.com/v3.0/me/permissions
        info:
            url:            https://graph.facebook.com/v3.0/me
            fields:
                -           id
                -           email
                -           first_name
                -           last_name
                -           name
                -           gender
                -           locale
                -           timezone
                -           link
        picture:
            url:            https://graph.facebook.com/v3.0/me/picture
            query:
                redirect:   false
                width:      200
                height:     200

github:
    auth:
        auth_url:           https://github.com/login/oauth/authorize
        scope_separator:    " "
        query_params:
            redirect_uri:   /xxxxxxxx
            client_id:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            scope:
                -           user:email
    token:
        token_url:          https://github.com/login/oauth/access_token
        client_secret:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api:
        user_info_url:      https://api.github.com/user
        user_email_url:     https://api.github.com/user/emails

# Yahoo has implemented the open id standardization for its Oauth prototol
# API endpoints have to be updated based on this Discovery Document
# https://login.yahoo.com/.well-known/openid-configuration
yahoo:
    auth:
        auth_url:           https://api.login.yahoo.com/oauth2/request_auth
        scope_separator:    " "
        query_params:
            redirect_uri:   /xxxxxxxx
            response_type:  code
            client_id:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            scope:
                -           openid
    token:
        token_url:          https://api.login.yahoo.com/oauth2/get_token
        client_secret:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api:
        user_info_url:      https://social.yahooapis.com/v1/user/me/profile

# Microsoft has implemented the open id standardization for its Oauth prototol
# API endpoints have to be updated based on this Discovery Document
# https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
microsoft:
    auth:
        auth_url:           https://login.microsoftonline.com/common/oauth2/v2.0/authorize
        scope_separator:    " "
        query_params:
            redirect_uri:   /xxxxxxxx
            response_type:  code
            response_mode:  query
            client_id:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            scope:
                -           openid
                -           email
                -           user.read
    token:
        token_url:          https://login.microsoftonline.com/common/oauth2/v2.0/token
        client_secret:      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api:
        user_info:
            url:            https://graph.microsoft.com/v1.0/me
        picture:
            meta_url:       https://graph.microsoft.com/beta/me/photo
            url:            https://graph.microsoft.com/beta/me/photo/$value
# The GET photo operation in beta supports a user's work, school, or personal accounts.
# The GET photo metadata operation, however, supports only the user's work or school accounts and not personal accounts.
# https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/profilephoto_get

# create:
#     google:               https://console.developers.google.com/apis/credentials
#     facebook:             https://developers.facebook.com/quickstarts/
#     github:               https://github.com/settings/applications
#     yahoo:                https://developer.yahoo.com/apps/create
#     microsoft:            https://apps.dev.microsoft.com
# revoke:
#     google:               https://security.google.com/settings/security/permissions
#     facebook:             https://www.facebook.com/settings?tab=applications
#     github:               https://github.com/settings/applications
#     yahoo:                ??
#     microsoft:            https://account.live.com/consent/Manage